baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Programming Dungeon'
theme = 'basic'

[params]
author = "Alexander Luna"
description = "Improving my programming skills"
googleAnalytics = "UA-xxxxxxxxxxxx"
gh_url = "https://api.github.com/users"
gh_user = "alexanderluna"
