baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Programming Dungeon'
theme = 'basic'
disqusShortname = "programming-dungeon"
pygmentsUseClasses = true

[params]
author = "Alexander Luna"
description = "Improving my programming skills"
googleAnalytics = "UA-xxxxxxxxxxxx"
gh_url = "https://api.github.com/users"
gh_user = "alexanderluna"

[permalinks]
posts = "posts/:year/:month/:slug/"
year = "/posts/:slug/"
month = "/posts/:slug/"

[taxonomies]
year = "year"
month = "month"
tag = "tags"
category = "categories"

[deployment]
[[deployment.targets]]
name = "prod"
URL = "s3://BUCKET_NAME?region=YOUR_REGION"

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|js|css)$"
gzip = true
